- job:
    name: heat-functional-devstack-base
    parent: legacy-dsvm-base
    run: playbooks/devstack/functional/run.yaml
    post-run: playbooks/devstack/functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/ceilometer
      - openstack/devstack-plugin-amqp1
      - openstack/heat
      - openstack/heat-tempest-plugin
      - openstack/neutron
      - openstack/octavia
      - openstack/oslo.messaging
      - openstack/python-barbicanclient
      - openstack/python-heatclient
      - openstack/heat-agents
      - openstack/python-zaqarclient
      - openstack/zaqar
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^heat/locale/.*$
      - ^heat/tests/.*$
      - ^releasenotes/.*$
    vars:
      configure_swap_size: 8192
      disable_convergence: 'false'
      sql: mysql
      use_amqp1: 0
      use_apache: 1
      use_python3: 0
      branch_override: default

- job:
    name: heat-functional-orig-mysql-lbaasv2
    parent: heat-functional-devstack-base
    voting: false
    vars:
      disable_convergence: 'true'

- job:
    name: heat-functional-convg-mysql-lbaasv2
    parent: heat-functional-devstack-base
    voting: false

- job:
    name: heat-functional-convg-mysql-lbaasv2-non-apache
    parent: heat-functional-devstack-base
    voting: false
    vars:
      use_apache: 0

- job:
    name: heat-functional-convg-mysql-lbaasv2-py3
    parent: heat-functional-devstack-base
    vars:
      use_python3: 1

- job:
    name: grenade-heat
    parent: grenade
    required-projects:
      - opendev.org/openstack/heat
      - opendev.org/openstack/heat-tempest-plugin
      - opendev.org/openstack/python-heatclient
    vars:
      configure_swap_size: 8192
      devstack_services:
        h-api: true
        h-api-cfn: true
        h-eng: true
        heat: true
      # We do run a list of tests after upgrade. This is just to bypass the req from parent.
      tempest_test_regex: ^tempest\.api\.identity\.v3\.test_tokens
      tox_envlist: all
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
      tempest_plugins:
        - heat-tempest-plugin

- job:
    name: grenade-heat-multinode
    parent: grenade-heat
    nodeset: openstack-two-node-bionic
    voting: false

- project:
    queue: heat
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    # All py2 functional and grenade jobs are set to non-voting
    # until bug #1922597 and devstack py2 issues are fixed.
    check:
      jobs:
        - grenade-heat
        - grenade-heat-multinode
        - heat-functional-orig-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2
        - heat-functional-convg-mysql-lbaasv2-non-apache
        - heat-functional-convg-mysql-lbaasv2-py3
    gate:
      jobs:
        - grenade-heat
        - heat-functional-convg-mysql-lbaasv2-py3
